[2016-09-06 21:56:08,588] [ERROR] [__main__-4608.log] [psia_wrap.py:try_get_device_info:448] [try device id: ip:172.16.1.195 pid:4608 threadid:9988 exception fail!!!]
